image: ubuntu:17.10

before_script:
- bash ci/docker_install.sh > /dev/null

test:app:
  #when: manual
  before_script:
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
  - php composer.phar install
  script:
  -  cd api/Tests
  -  phpunit
  -  cd ../../ci
  -  bash build_zip.sh
  #-  php deploy_release_to_github.php